"""
GitHub integration for the AI orchestration system.

Handles:
  - Branch pushes
  - Pull request creation (if AUTO_CREATE_PR=true)
  - PR URL tracking on the task packet
"""

import subprocess
from pathlib import Path

from runner.config import BASE_DIR, GITHUB_REPO, GITHUB_TOKEN, AUTO_CREATE_PR
from runner.logger import github_log, log_execution_event
from runner.schemas import save_task


def _run(args: list[str], cwd: Path = BASE_DIR) -> tuple[int, str, str]:
    result = subprocess.run(
        args, cwd=str(cwd), capture_output=True, text=True
    )
    return result.returncode, result.stdout.strip(), result.stderr.strip()


def push_branch(branch_name: str, task_id: str) -> bool:
    """Push the task branch to origin. Returns True on success."""
    github_log.info("[%s] Pushing branch: %s", task_id, branch_name)
    rc, out, err = _run(["git", "push", "-u", "origin", branch_name])
    if rc != 0:
        github_log.error("[%s] Push failed: %s", task_id, err)
        return False
    github_log.info("[%s] Branch pushed successfully", task_id)
    log_execution_event(task_id, "BRANCH PUSHED", branch_name)
    return True


def create_pull_request(task: dict, review: dict) -> str | None:
    """
    Create a GitHub PR using the `gh` CLI tool.
    Returns the PR URL if successful, None otherwise.

    Requires `gh` CLI to be authenticated (gh auth login).
    """
    task_id = task["task_id"]
    branch_name = task.get("branch_name", "")

    if not branch_name:
        github_log.warning("[%s] No branch name on task — cannot create PR", task_id)
        return None

    # Build PR title and body
    title = f"[{task_id}] {task.get('title', 'AI Task')}"

    criteria_met = "\n".join(f"- {c}" for c in review.get("criteria_met", []))
    next_steps = "\n".join(f"- {s}" for s in review.get("next_steps", []))

    body = (
        f"## Task\n{task.get('request', '')}\n\n"
        f"## Goals\n" + "\n".join(f"- {g}" for g in task.get("goals", [])) + "\n\n"
        f"## Review Score: {review.get('score', '?')}/10\n"
        f"{review.get('reasoning', '')}\n\n"
        f"## Criteria Met\n{criteria_met or '_none_'}\n\n"
        f"## Next Steps\n{next_steps or '_none_'}\n\n"
        f"---\n_Generated by AI Orchestration System_"
    )

    github_log.info("[%s] Creating PR: %s", task_id, title)
    rc, out, err = _run([
        "gh", "pr", "create",
        "--title", title,
        "--body", body,
        "--base", "main",
        "--head", branch_name,
    ])

    if rc != 0:
        github_log.error("[%s] PR creation failed: %s", task_id, err)
        return None

    pr_url = out.strip()
    github_log.info("[%s] PR created: %s", task_id, pr_url)
    log_execution_event(task_id, "PR CREATED", pr_url)
    return pr_url


def handle_post_approval(task: dict, review: dict) -> dict:
    """
    After a task is approved:
    1. Push the branch to origin
    2. Optionally create a PR (if AUTO_CREATE_PR is enabled)
    3. Update the task packet with PR URL
    Returns the updated task dict.
    """
    task_id = task["task_id"]
    branch_name = task.get("branch_name", "")

    if not branch_name:
        github_log.warning("[%s] No branch name — skipping GitHub operations", task_id)
        return task

    # Push the branch
    push_ok = push_branch(branch_name, task_id)

    if push_ok and AUTO_CREATE_PR:
        pr_url = create_pull_request(task, review)
        if pr_url:
            task["pr_url"] = pr_url
            save_task(task)

    return task
